name: Build and Publish Docker Image

# Déclenche l'action à chaque fois que tu envoies du code sur la branche "main"
on:
  push:
    branches: [ "main" ]

# Définition de la tâche
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # Autorisations nécessaires pour publier sur le GitHub Container Registry (GHCR)
    permissions:
      contents: read
      packages: write

    steps:
      - name: 📥 Télécharger le code source
        uses: actions/checkout@v4

      - name: 🔑 Connexion au registre GitHub (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Extraction automatique des métadonnées (Nom et Tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: 🚀 Construction et Publication de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}